/**
 * The weekly postcard from the baby: one short note a week, written as if the
 * baby sent it to both of them. Each note only uses facts from that week’s
 * “Baby this week” card. The wording is reviewed in the “Bloom baby postcards” doc.
 */
export const POSTCARDS: Record<number, string> = {
  4: 'Hello! I’m only a tiny cluster of cells, but I’ve found a cosy spot and I’m settling in.',
  5: 'Big news from in here: my heart is starting to form. It’s a very small heart, but it’s a start.',
  6: 'My heart is beating now! I’m also growing little buds that will become my arms and legs.',
  7: 'My brain is making about 100 new cells a minute. Busy, busy, busy.',
  8: 'I’ve started making tiny movements. You won’t feel them for ages, but I’m practising.',
  9: 'I’ve got a little face now: eyes, a mouth, and a tongue with tiny taste buds.',
  10: 'My heart is racing along at about 180 beats a minute. That’s just my speed for now.',
  11: 'My fingers and toes are separating, and tiny nails are on the way. I’m kicking already, just too small to feel.',
  12: 'All my parts are in place. From here, my job is mostly growing. I’m good at it.',
  13: 'I’m wriggling a lot in here, and I’ve started practising swallowing. So much to learn!',
  14: 'I’m kicking and stretching all day. You can’t feel it yet. Just wait.',
  15: 'I can hear your heartbeat now. It’s my favourite sound so far.',
  16: 'I can frown, squint and make tiny fists. I’m practising all my faces for you.',
  17: 'I’m growing fingerprints that nobody else in the world has. Just mine.',
  18: 'I might hear voices and music from outside now. Feel free to sing. I won’t judge.',
  19: 'I’m busier at some times than others now. I’m finding my own routine.',
  20: 'Halfway there! I’m wrapped in a waxy coat that keeps my skin safe in here.',
  21: 'I’ve started having sleepy times and awake times. Guess which one I like best?',
  22: 'I can taste a little of what you eat. No pressure, but I’m curious about everything.',
  23: 'My arms and legs are in proportion now. When I kick, you might even see your bump move.',
  24: 'I’m putting on weight every week and getting stronger. Keep talking to me, I’m listening.',
  25: 'Those little rhythmic taps? Hiccups. I’ve also been doing somersaults. Lots of room in here!',
  26: 'My eyes are starting to open! Everything’s a bit dim, but it’s a start.',
  27: 'I’m filling out nicely. I might wiggle when I hear your voice or some music.',
  28: 'My heart has slowed to about 140 beats a minute, and I sleep a lot. Growing is tiring!',
  29: 'I’m all here now. These weeks are for growing strong and getting cosy.',
  30: 'My eyes can focus now, and I can tell light from dark. I can’t wait to see your faces.',
  31: 'I’ve been sucking my fingers and doing the odd somersault. Getting plumper by the day.',
  32: 'My main job now is putting on weight. Pass the snacks.',
  33: 'My bones are getting harder, except my head, which stays soft for the big day.',
  34: 'I’m getting ready for the big day, and my waxy coat is getting thicker.',
  35: 'It’s getting snug in here, so it’s fewer big kicks and more wriggles and stretches.',
  36: 'My lungs are nearly ready, and I can suck and swallow. Practice makes perfect.',
  37: 'Full term! I’ll be ready to feed and breathe when the day comes. No rush, though.',
  38: 'I’m practising sucking, swallowing and grasping. Getting ready to meet you.',
  39: 'I’m still growing right up until I arrive. Almost time to say hello in person.',
  40: 'Due date week! I’ll come when I’m ready. Keep noticing my moves until then.',
  41: 'I’m fully ready, just taking my time. See you very soon.',
};
